// Country flag emojis mapping
export const COUNTRY_FLAGS: Record<string, string> = {
  'Ethiopia': '🇪🇹',
  'Nepal': '🇳🇵',
  'Kenya': '🇰🇪',
  'Pakistan': '🇵🇰',
  'Philippines': '🇵🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Thailand': '🇹🇭',
  'Brazil': '🇧🇷',
  'Mexico': '🇲🇽',
  'Argentina': '🇦🇷',
  'South Africa': '🇿🇦',
  'Russia': '🇷🇺',
  'Poland': '🇵🇱',
  'Spain': '🇪🇸',
  'Italy': '🇮🇹',
  'France': '🇫🇷',
  'UK': '🇬🇧',
  'Canada': '🇨🇦',
  'Germany': '🇩🇪',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'China': '🇨🇳',
  'USA': '🇺🇸',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'Netherlands': '🇳🇱',
  'Denmark': '🇩🇰',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Finland': '🇫🇮',
  'Ireland': '🇮🇪',
  'Portugal': '🇵🇹',
  'Greece': '🇬🇷',
  'Romania': '🇷🇴',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Bulgaria': '🇧🇬',
  'Hungary': '🇭🇺',
  'Czech Republic': '🇨🇿',
  'Ukraine': '🇺🇦',
  'Singapore': '🇸🇬',
  'Malaysia': '🇲🇾',
  'Colombia': '🇨🇴',
  'Peru': '🇵🇪',
  'Chile': '🇨🇱',
  'Ecuador': '🇪🇨',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Guatemala': '🇬🇹',
  'El Salvador': '🇸🇻',
  'Turkey': '🇹🇷',
  'Lithuania': '🇱🇹',
  'Latvia': '🇱🇻',
  'Estonia': '🇪🇪',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Bosnia': '🇧🇦',
  'North Macedonia': '🇲🇰',
  'Albania': '🇦🇱',
  'Belarus': '🇧🇾',
  'Moldova': '🇲🇩',
  'Iceland': '🇮🇸',
  'Luxembourg': '🇱🇺',
  'Monaco': '🇲🇨',
  'Malta': '🇲🇹',
  'Cyprus': '🇨🇾',
  'San Marino': '🇸🇲',
  'Vatican City': '🇻🇦',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Uruguay': '🇺🇾',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',
  'Venezuela': '🇻🇪',
  'Morocco': '🇲🇦',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Egypt': '🇪🇬',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  'Senegal': '🇸🇳',
  'Tanzania': '🇹🇿',
  'Uganda': '🇺🇬',
  'Zimbabwe': '🇿🇼',
  'Zambia': '🇿🇲',
  'Angola': '🇦🇴',
  'Cameroon': '🇨🇲',
  'Mongolia': '🇲🇳',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Sri Lanka': '🇱🇰',
  'Taiwan': '🇹🇼',
  'Afghanistan': '🇦🇫',
  'Bangladesh': '🇧🇩',
  'India': '🇮🇳',
};

export const getCountryFlag = (cityCountryName: string): string => {
  // Extract country name from "City, Country" format
  const parts = cityCountryName.split(',');
  if (parts.length < 2) {
    // If no comma, might be single country name
    return COUNTRY_FLAGS[cityCountryName.trim()] || '🌍';
  }
  
  const country = parts[parts.length - 1].trim();
  return COUNTRY_FLAGS[country] || '🌍';
};
